export const fakeData = [
    {
        "athlete": "شنا",
        "age": 23,
        "country": "ایران",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "فوتبال",
        "age": 23,
        "country": "آمریکا",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Red'
    },
    {
        "athlete": "کاراته",
        "age": 23,
        "country": "ژاپن",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "وابیبال",
        "age": 23,
        "country": "چین",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Green'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },
    {
        "athlete": "شنا",
        "age": 23,
        "country": "قطر",
        "year": 2008,
        "date": "24/08/2008",
        "sport": "شنا ",
        "gold": 8,
        "silver": 0,
        "bronze": 0,
        "total": 8,
        'color' : 'Blue'
    },


    
] 